# 打印sql
logging:
  level:
    com.hxxzt.recruitment.system.mapper: debug
    com.hxxzt.recruitment.business.mapper: debug

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.199.78.3:3306/uoffer?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: uoffer
    password: neaJ5Dh4RsRWB463
    hikari:
      # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      connection-timeout: 30000
      # 最小连接数
      minimum-idle: 5
      # 最大连接数
      maximum-pool-size: 20
      # 自动提交
      auto-commit: true
      # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      idle-timeout: 600000
      # 连接池名字
      pool-name: DateSourceHikariCP
      # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  redis:
    host: 121.199.78.3
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 47hAc5NiNKze5KcX
    # 连接超时时间（毫秒）
    timeout: 10000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
penint:
  resourcePath:
    image: file:/Users/planet/Documents/recruitment/image/
    uploadAvatar: /Users/planet/Documents/recruitment/image/avatar
    AvatarUrl: /image/avatar
    uploadBusinessLicense: /Users/planet/Documents/recruitment/image/businessLicense
    businessLicenseUrl: /image/businessLicense